install diki from the master branch and clone it

diff --git a/docs/deployment/content/remote-local-setup-with-jail.yaml b/docs/deployment/content/remote-local-setup-with-jail.yaml
--- a/docs/deployment/content/remote-local-setup-with-jail.yaml
+++ b/docs/deployment/content/remote-local-setup-with-jail.yaml
@@ -162,11 +162,11 @@ spec:
                wget -N "https://github.com/bronze1man/yaml2json/releases/download/$VERSION/yaml2json_linux_amd64"
                cp yaml2json_linux_amd64 /usr/local/bin/yaml2json
                chmod +x /usr/local/bin/yaml2json
-          echo diki
-               VERSION=$(curl -sL -H 'Accept: application/json' https://github.com/gardener/diki/releases/latest | jq '.tag_name' -r)
-               wget -N "https://github.com/gardener/diki/releases/download/$VERSION/diki-linux-amd64"
-               cp diki-linux-amd64 /usr/local/bin/diki
-               chmod +x /usr/local/bin/diki
+          # echo diki
+          #      VERSION=$(curl -sL -H 'Accept: application/json' https://github.com/gardener/diki/releases/latest | jq '.tag_name' -r)
+          #      wget -N "https://github.com/gardener/diki/releases/download/$VERSION/diki-linux-amd64"
+          #      cp diki-linux-amd64 /usr/local/bin/diki
+          #      chmod +x /usr/local/bin/diki
           cd
 
           echo delve
@@ -560,7 +560,22 @@ spec:
               sleep 1h
               exit 1
             fi
+
+            cd ~/go/src/github.com/gardener
+            [ -d diki/.git ] || git clone -q https://github.com/gardener/diki.git
+            cd diki
+            git fetch
+            git reset --hard
+
+            # apply patches
+            yq < imagevector/images.yaml '.images[0].repository = "localhost:5001/gardener/diki-ops"' > /tmp/images.yaml
+            mv /tmp/images.yaml imagevector/images.yaml
+            sed -i 's/nsenter --all/nsenter -m -u -i -n -p -C/g' pkg/kubernetes/pod/privileged.go
+
+            make build-linux-amd64
           DEMO_EOF
+
+          cp /home/demo/go/src/github.com/gardener/diki/bin/diki-linux-amd64 /usr/local/bin/diki
 
           mkdir -p /etc/docker
           echo '{"insecure-registries" : [
@@ -671,6 +686,8 @@ spec:
             mkdir -p scripts
             cp /usr/local/bin/tmux_functions.sh scripts
             cp /usr/local/bin/is_tmux_window_shown.sh scripts
+            mkdir -p bin
+            cp ~/go/src/github.com/gardener/diki/bin/diki-linux-amd64 bin/diki
 
             sed 's/^  //' <<DOCKERFILE > ~/go/src/github.com/gardener/gardener/cell/Dockerfile
               FROM alpine:3.20
@@ -730,12 +747,12 @@ spec:
                        wget "https://github.com/bronze1man/yaml2json/releases/download/\$VERSION/yaml2json_linux_amd64"        && \\
                        mv yaml2json_linux_amd64 /usr/local/bin/yaml2json                                                       && \\
                        chmod +x /usr/local/bin/yaml2json
-              RUN echo diki                                                                                                    && \\
-                       VERSION=$(curl -sL -H 'Accept: application/json' https://github.com/gardener/diki/releases/latest \
-                                                                                             | jq '.tag_name' -r)              && \\
-                       wget -N "https://github.com/gardener/diki/releases/download/\$VERSION/diki-linux-amd64"                 && \\
-                       cp diki-linux-amd64 /usr/local/bin/diki                                                                 && \\
-                       chmod +x /usr/local/bin/diki
+              # RUN echo diki                                                                                                    && \\
+              #          VERSION=$(curl -sL -H 'Accept: application/json' https://github.com/gardener/diki/releases/latest \
+              #                                                                                | jq '.tag_name' -r)              && \\
+              #          wget -N "https://github.com/gardener/diki/releases/download/\$VERSION/diki-linux-amd64"                 && \\
+              #          cp diki-linux-amd64 /usr/local/bin/diki                                                                 && \\
+              #          chmod +x /usr/local/bin/diki
 
               RUN adduser --disabled-password --gecos '' demo
               USER demo
@@ -1115,6 +1132,7 @@ spec:
               RUN chmod +x ~/prepare-cell.sh
 
               COPY --chown=demo:demo gardener /home/demo/go/src/github.com/gardener/gardener
+              COPY bin/diki /usr/local/bin/diki
             DOCKERFILE
 
             cd -
@@ -1616,9 +1634,25 @@ spec:
                 DEMO_EOF
               NETWORK_EOF
             EOF
+            new_pane "buid and push the patched diki-ops image" Enter <<"EOF"
+              flag_wait rootless_kind_operator_up_ready &&
+              stopwatch_start &&
+              sed 's/^  //' <<"NETWORK_EOF" | xargs -d '\0' \
+              nsenter -t $(DOCKER_HOST= docker inspect --format '{{ .State.Pid }}' ubuntu_systemd_rootless_docker) -n bash -c; stopwatch_stop
+                sed 's/^  //' <<"DEMO_EOF" | xargs -d '\0' \
+                su -l demo -c -l
+                  set -e
+                  cd ../diki
+                  retry nice docker build -t localhost:5001/gardener/diki-ops:$(cat VERSION) --progress plain .
+                  retry nice docker push localhost:5001/gardener/diki-ops:$(cat VERSION)
+                  flag_notify rootless_diki_ops_patched
+                DEMO_EOF
+              NETWORK_EOF
+            EOF
 
             new_window "make operator-(seed)-up" "make operator-up" Enter <<"EOF"
               flag_wait rootless_etcd_druid_patched &&
+              flag_wait rootless_diki_ops_patched &&
               stopwatch_start &&
               sed 's/^  //' <<"NETWORK_EOF" | xargs -d '\0' \
               nsenter -t $(DOCKER_HOST= docker inspect --format '{{ .State.Pid }}' ubuntu_systemd_rootless_docker) -n bash -c; stopwatch_stop
@@ -2465,10 +2499,85 @@ spec:
                 stopwatch_stop
               fi
             EOF
+            new_pane "configure diki" Enter <<"EOF"
+              if ! is_state_tested; then
+                time flag_wait rootless_shoot_ready &&
+                stopwatch_start &&
+                g target --shoot local &&
+                eval $(gardenctl kubectl-env bash) &&
+                sed 's/^  //' <<DIKI_EOF > /tmp/diki.yaml && flag_notify rootless_shoot_diki_config_ready; stopwatch_stop
+                  providers:
+                  - id: gardener
+                    name: Gardener
+                    metadata:
+                      # foo: bar
+                    args:
+                      shootKubeconfigPath: $KUBECONFIG
+                      seedKubeconfigPath: /home/demo/.kube/config
+                      shootName: local
+                      shootNamespace: shoot--local--local
+                    rulesets:
+                    - id: disa-kubernetes-stig
+                      name: DISA Kubernetes Security Technical Implementation Guide
+                      version: v2r1
+                      ruleOptions:
+                      - ruleID: "242445"
+                        args:
+                          expectedFileOwner:
+                            # users and groups default to ["0"]
+                            #
+                            # Gardener images use distroless nonroot user with ID 65532
+                            # https://github.com/GoogleContainerTools/distroless/blob/main/base/base.bzl#L8
+                            users: ["0", "65532"]
+                            groups: ["0", "65532"]
+                      - ruleID: "242446"
+                        args:
+                          expectedFileOwner:
+                            # users and groups default to ["0"]
+                            #
+                            # Gardener images use distroless nonroot user with ID 65532
+                            # https://github.com/GoogleContainerTools/distroless/blob/main/base/base.bzl#L8
+                            users: ["0", "65532"]
+                            groups: ["0", "65532"]
+                      - ruleID: "242451"
+                        args:
+                          # kubeProxyDisabled: true
+                          expectedFileOwner:
+                            # users and groups default to ["0"]
+                            #
+                            # Gardener images use distroless nonroot user with ID 65532
+                            # https://github.com/GoogleContainerTools/distroless/blob/main/base/base.bzl#L8
+                            users: ["0", "65532"]
+                            groups: ["0", "65532"]
+                      - ruleID: "245543"
+                        args:
+                          acceptedTokens:
+                          - user: "health-check"
+                            uid: "health-check"
+                  output:
+                    minStatus: Passed
+                DIKI_EOF
+              fi
+            EOF
+            new_pane "run diki" Enter <<"EOF"
+              if ! is_state_tested; then
+                flag_wait rootless_shoot_diki_config_ready &&
+                diki run \
+                  --config=/tmp/diki.yaml \
+                  --provider=gardener \
+                  --ruleset-id=disa-kubernetes-stig \
+                  --ruleset-version=v2r1 \
+                  --output=/tmp/disa-k8s-stigs-report.json &&
+                # TODO: Check the report and fail if necessary
+                echo "Report summary:" &&
+                jq -r '.providers[].rulesets[].rules[].checks[].status' < /tmp/disa-k8s-stigs-report.json | sort | uniq -c &&
+                flag_notify rootless_shoot_diki_ready
+              fi
+            EOF
             new_pane "Delete" Enter <<"EOF"
               export KUBECONFIG=$PWD/example/operator/virtual-garden/kubeconfig
               if ! is_state_tested; then
-                time flag_wait rootless_shoot_ha_ready &&
+                time flag_wait rootless_shoot_diki_ready &&
                 stopwatch_start &&
                 k annotate shoot local -n garden-local 'confirmation.gardener.cloud/deletion=true' &&
                 time k delete shoot local -n garden-local &&
