fail after 5 minutes

diff --git a/docs/deployment/content/remote-local-setup-daemonset.yaml b/docs/deployment/content/remote-local-setup-daemonset.yaml
--- a/docs/deployment/content/remote-local-setup-daemonset.yaml
+++ b/docs/deployment/content/remote-local-setup-daemonset.yaml
@@ -42,6 +42,10 @@ spec:
             fi
             sleep $i
             let i=i*2
+            if [ $i -gt 300 ]; then
+              echo "failed to resolve registry service IP"
+              exit 1
+            fi
           done
           sed 's/^  //' <<NSENTER_EOF | xargs -0 nsenter -t 1 -n -m /bin/sh -c
             set -ex
